export const DummyActions: Action[] = [{ systemName: "action1Main", infix: "abcd" , isActive:false , id: "001" }, 
{ systemName: "action1OnAfterSave", infix: "efgh" , isActive: false , id: "002"},
{ systemName: "action1OnError", infix: "ıijk" , isActive: false ,  id: "003"}, 
{ systemName: "action2Main", infix: "ıijk" , isActive: true , id: "004"},
{ systemName: "action2OnError", infix: "lm" , isActive: false , id: "005"}, 
{ systemName: "action2OnAfterSave", infix: "no" , isActive: true , id: "006"},
{ systemName: "action2OnError", infix: "öp" , isActive: true , id: "007"}, 
{ systemName: "action3Main", infix: "rs" , isActive: false , id: "008"},
{ systemName: "action3OnAfterSave", infix: "şt" , isActive: true , id: "009"}, 
{systemName: "action3OnError" , infix: "uü" , isActive: false , id: "010"}]